version: '3.8'

services:
  assistente-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=5000
    volumes:
      - ../data:/app/data
    restart: unless-stopped
    
  assistente-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - assistente-api
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    restart: unless-stopped

